env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.2
      before_script:
        - xcrun simctl delete BE8E0914-5B5F-45C2-8C99-879894AF72B0
      script:
        - pod lib lint --swift-version=3.0
      env:
        - JOB=PODSPEC
    - os: osx
      language: objective-c
      osx_image: xcode8.2
      before_script:
        - xcrun simctl delete BE8E0914-5B5F-45C2-8C99-879894AF72B0
      script:
        - rake "build[build-for-testing test-without-building, Himotoki-macOS, macosx, arch=x86_64]"
        - rake "build[build-for-testing test-without-building, Himotoki-iOS, iphonesimulator, name=iPhone 6s]"
        - rake "build[build-for-testing test-without-building, Himotoki-tvOS, appletvsimulator, name=Apple TV 1080p]"
        - rake "build[build, Himotoki-watchOS, watchsimulator, name=Apple Watch - 38mm]"
    - os: osx
      language: generic
      osx_image: xcode8.2
      script:
        - swift build
        - swift test
      env:
        - JOB=SWIFTPM_DARWIN
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build
        - swift test
      env:
        - JOB=SWIFTPM_LINUX
notifications:
  email: false
